; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = upesy_wrover

[env]
platform = espressif32@7.0.1
board = upesy_wrover
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@2.8
  bblanchon/ArduinoJson@7.2.0
  https://github.com/Freenove/Freenove_WS2812_Lib_for_ESP32.git#v1.0.5

[env:upesy_wrover]
build_src_filter = +<main.cpp>

; Select this environment only for the SECOND ESP32.
[env:actuator_board]
build_src_filter = +<actuator_main.cpp>
